import type { Scenario } from '../types/content'

// Scenario dialogues for mock-conversation practice. Each 'you' turn is
// graded against acceptableResponses via lib/grading.ts fuzzy matching.
// Branches let a scenario fork based on which reply the learner picks.

export const scenarios: Scenario[] = [
  {
    id: 'sc-subcontractor-delay',
    domain: 'subcontractors',
    register: 'direct',
    title: 'A subcontractor calls about a delay',
    setup: 'Your electrical subcontractor calls you mid-afternoon. Something has come up on their end.',
    startTurnId: 't1',
    turns: [
      {
        id: 't1',
        speaker: 'them',
        hebrew: 'היי, זה דני מהחשמל. יש לנו בעיה עם האספקה.',
        transliteration: 'hey, ze Dani mehachashmal. yesh lanu be\'aya im ha\'aspaka.',
        english: "Hey, it's Dani from electrical. We have a problem with the delivery.",
      },
      {
        id: 't2',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Ask: why is there a delay?',
        acceptableResponses: ['למה יש איחור?', 'lama yesh ichur?'],
      },
      {
        id: 't3',
        speaker: 'them',
        hebrew: 'הספק לא שלח את החומרים בזמן. זה ייקח עוד יומיים.',
        transliteration: 'hasapak lo shalach et hachomarim bazman. ze yikach od yomayim.',
        english: 'The supplier did not send the materials on time. It will take two more days.',
      },
      {
        id: 't4',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Say: This is not okay, I need this today.',
        acceptableResponses: ['זה לא בסדר, אני צריך את זה היום', 'ze lo beseder, ani tzarich et ze hayom'],
        branches: [
          { choiceHebrew: 'זה לא בסדר, אני צריך את זה היום', choiceEnglish: 'This is not okay, I need this today', nextTurnId: 't5a' },
          { choiceHebrew: 'בסדר, תעדכן אותי מחר', choiceEnglish: "Okay, update me tomorrow", nextTurnId: 't5b' },
        ],
      },
      {
        id: 't5a',
        speaker: 'them',
        hebrew: 'אני מבין. אני אנסה למצוא פתרון ואעדכן אותך היום בערב.',
        transliteration: 'ani mevin. ani anase limtzo pitaron ve\'a\'adken otcha hayom ba\'erev.',
        english: 'I understand. I will try to find a solution and update you this evening.',
      },
      {
        id: 't5b',
        speaker: 'them',
        hebrew: 'סבבה, אעדכן אותך מחר בבוקר.',
        transliteration: "sababa, a'adken otcha machar baboker.",
        english: "Sounds good, I'll update you tomorrow morning.",
      },
    ],
  },
  {
    id: 'sc-inspector-visit',
    domain: 'client-inspector',
    register: 'formal',
    title: 'A building inspector visits the site',
    setup: 'A municipal building inspector arrives unannounced to check progress against the approved plan.',
    startTurnId: 'i1',
    turns: [
      {
        id: 'i1',
        speaker: 'them',
        hebrew: 'שלום, אני מהוועדה המקומית לתכנון ובנייה. אני צריך לבדוק את ההתקדמות.',
        transliteration: "shalom, ani mehava'ada hamekomit letichnun uvniya. ani tzarich livdok et hahitkadmut.",
        english: "Hello, I'm from the local planning and building committee. I need to check on progress.",
      },
      {
        id: 'i2',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Say: Everything is progressing according to plan.',
        acceptableResponses: ['הכול מתקדם לפי התוכנית', 'hakol mitkadem lefi hatochnit'],
      },
      {
        id: 'i3',
        speaker: 'them',
        hebrew: 'יש לי הערה לגבי חריגה קטנה בקומה השנייה.',
        transliteration: 'yesh li he\'ara legabei chariga ktana bakoma hashniya.',
        english: 'I have a note about a small violation on the second floor.',
      },
      {
        id: 'i4',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Say: We are required to correct the violation, and ask if it is possible to schedule a follow-up meeting.',
        acceptableResponses: [
          'אנחנו נדרשים לתקן את החריגה, האם ניתן לתאם פגישה?',
          'anachnu nidrashim letaken et hachariga, ha\'im niten letaem pgisha?',
        ],
      },
      {
        id: 'i5',
        speaker: 'them',
        hebrew: 'בסדר גמור. תודה על שיתוף הפעולה.',
        transliteration: 'beseder gamur. toda al shituf hape\'ula.',
        english: 'That works. Thank you for the cooperation.',
      },
    ],
  },
  {
    id: 'sc-apartment-rental',
    domain: 'housing',
    register: 'formal',
    title: 'Calling about an apartment rental',
    setup: "You're calling a landlord about an apartment listing you found.",
    startTurnId: 'a1',
    turns: [
      {
        id: 'a1',
        speaker: 'them',
        hebrew: 'שלום, מדברים על הדירה ברחוב הרצל?',
        transliteration: 'shalom, medabrim al hadira birchov Herzl?',
        english: "Hello, is this about the apartment on Herzl Street?",
      },
      {
        id: 'a2',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Ask: how much is the rent per month?',
        acceptableResponses: ['כמה עולה השכירות בחודש?', 'kama ole haschirut bachodesh?'],
      },
      {
        id: 'a3',
        speaker: 'them',
        hebrew: 'חמשת אלפים שקל בחודש, כולל ועד בית.',
        transliteration: "chameshet alafim shekel bachodesh, kolel va'ad bayit.",
        english: '5,000 shekels a month, including the building committee fee.',
      },
      {
        id: 'a4',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Ask: when can we move into the apartment?',
        acceptableResponses: ["מתי אפשר לעבור דירה?", "matai efshar la'avor dira?"],
      },
      {
        id: 'a5',
        speaker: 'them',
        hebrew: 'אפשר לחתום על חוזה השבוע ולעבור בתחילת החודש הבא.',
        transliteration: 'efshar lachtom al chuze hashavua ve\'la\'avor bitchilat hachodesh haba.',
        english: 'We can sign a lease this week and move in at the start of next month.',
      },
    ],
  },
  {
    id: 'sc-material-order',
    domain: 'subcontractors',
    register: 'formal',
    title: 'Ordering materials from a supplier',
    setup: "You're calling a materials supplier to place an order and confirm a deadline.",
    startTurnId: 'm1',
    turns: [
      {
        id: 'm1',
        speaker: 'them',
        hebrew: 'שלום, איך אפשר לעזור?',
        transliteration: 'shalom, eich efshar la\'azor?',
        english: 'Hello, how can I help?',
      },
      {
        id: 'm2',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Say: I need a price quote by Thursday.',
        acceptableResponses: ['אני צריך הצעת מחיר עד יום חמישי', 'ani tzarich hatzaat mechir ad yom chamishi'],
      },
      {
        id: 'm3',
        speaker: 'them',
        hebrew: 'אין בעיה, אשלח היום. כמה חומרי גלם אתם צריכים?',
        transliteration: "ein be'aya, ashlach hayom. kama chomrei gelem atem tzrichim?",
        english: "No problem, I'll send it today. How much raw material do you need?",
      },
      {
        id: 'm4',
        speaker: 'you',
        hebrew: '',
        transliteration: '',
        english: 'Ask: how long will this take?',
        acceptableResponses: ['כמה זמן זה ייקח?', 'kama zman ze yikach?'],
      },
      {
        id: 'm5',
        speaker: 'them',
        hebrew: 'זמן האספקה הוא כשבוע.',
        transliteration: 'zman ha\'aspaka hu keshavua.',
        english: 'The lead time is about a week.',
      },
    ],
  },
]
